version: "3"
services:
  bot:
    build:
      context: .
    restart: on-failure
    env_file: variables.env

  database:
    image: mongo
    restart: always
    volumes:
      - "mongodata:/data/db"
    env_file: conf.env
